### ISSUE TITLE
clock.s doesn't compile

### ISSUE THREAD

**Issue by SiriGPT** [robsonde/Alius6502#3]
When compiling clock.s using vasm (Linux), it throws me this error.
```bash
vasm 1.4c (c) in 2002-2009 Volker Barthelmann
vasm 6502 cpu backend 0.5 (c) 2002,2006,2008,2009 Frank Wille
vasm oldstyle syntax module 0.8a (c) 2002-2009 Frank Wille
vasm binary output module 1.6 (c) 2002-2009 Volker Barthelmann

warning 2002 in line 36 of "demos/clock.s": trailing garbage in operand

warning 2002 in line 39 of "demos/clock.s": trailing garbage in operand

error 2006 in line 39 of "demos/clock.s": operand doesn't fit into 8-bits
```

**Comment by robsonde** [comment]
The error message shows you have a very old version of vasm.
Please install vasm 1.8K or newer and test again.

**Comment by SiriGPT** [comment]
Intresting. Please tell me the installation insturctions for linux to install a version above 1.8k so that I can test clock.s.
Thanks.

**Comment by SiriGPT** [comment]
Just checked, [sun.hasenbraten.de/vasm](url) is down and I can't find the binaries or source code to compile vasm anywhere else. Please suggest the best course of action for this
Thanks

**Comment by SiriGPT** [comment]
Finally! I found a binary source for vasm and got it working. will remove the warning but will add better installation instructions for Linux.
Thanks!
